### PR TITLE
workflows: add github review stats

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Signed-off-by: zhangjinpeng1987 <zhangjinpeng@pingcap.com>

ref https://github.com/marketplace/actions/pull-request-stats

### CODE REVIEW

**Review by GanZiheng — APPROVED** [review]
LGTM

**Comment by skyzh** [comment]
So we are now imposing a response time limit for PR reviews? 🤣

**Comment by zhangjinpeng1987** [comment]
> So we are now imposing a response time limit for PR reviews? 🤣

@skyzh so the contributor may easily & efficiently to find associated reviewers.

**Review by skyzh — APPROVED** [review]
Looks cool

**Pull request merged**
