### PR TITLE
add table implementation

### PR DESCRIPTION
**Pull request by skyzh**
- [x] iterator
- [x] table
- [x] iterator test
- [x] table test
- [x] table builder test
- [x] replace `usize` with `isize` in iterator

### CODE REVIEW

**Comment by skyzh** [comment]
The table module is nearly complete. I'll add tests and benchmark on Friday.

**Comment by skyzh** [comment]
This PR won't cover:
* merge iterator (will introduce on demand)
* concat iterator (will introduce on demand)
* bloom filter (next PR)

**Comment by skyzh** [comment]
There are some room for improvement, and will be solved later:
* use mmapfile instead of file+vec to improve read throughput
* auto calculate length, and eliminate the need to store `len` along with `Bytes` or `Vec`
* investigate whether it is necessary to implement some memory copy optimization (e.g. https://github.com/dgraph-io/badger/blob/master/table/iterator.go#L94 , seems not necessary in Rust)

**Comment by skyzh** [comment]
> You may need to split it into several small ones.
> 
> /cc @brson are you interested in reviewing the code?

This module is relatively hard to split, as table, iterator and builder needs to be put together to make all of them work. Anyway, if possible, I could make PR for builder and iterator+table separately, and make another PR to add tests for them.

**Comment by BusyJay** [comment]
Please do so. Our developing style is take small steps and move fast.

**Comment by Connor1996** [comment]
> You may need to split it into several small ones.
> 
> /cc @brson are you interested in reviewing the code?

I'd like to, too~

**Comment by skyzh** [comment]
I'll split this PR into:

* Refactor in table builder
* Block Iterator
* Iterator
* Table
* Tests and Benchmarks

**Pull request closed without merging**
